### PR TITLE
Add AppVeyor CI configuration

### PR DESCRIPTION
**Pull request by MikeGoldsmith**
Addresses Issue #81 
- requires contributor with Admin access to enable AppVeyor integration (which I do not)

### CODE REVIEW

**Comment by cwe1ss** [comment]
I don't have admin rights either - that's the main reason why I haven't done it yet. We'll have to talk to someone to figure out if we want to have this set up with one "OpenTracing" account etc. 

Anyway, the script should also set an empty VersionSuffix if it is built with a Github Tag. I was playing around with an AppVeyor script a few days ago and this is what I came up with: https://github.com/cwe1ss/csharp-netcore/blob/cweiss-appveyor/.appveyor.yml

Do you want to update this PR?

**Comment by MikeGoldsmith** [comment]
Happy to combine your AppVeyor script with this PR, I've done something very similar in the past.

I added @tedsuo as a reviewer to try and get some traction on having an admin enabling the AppVeyor integration.

**Comment by cwe1ss** [comment]
@tedsuo @bhs: I think this is what we would need to add CI integration on AppVeyor. We need this because Travis CI doesn't support Windows machines. This guide sets up one account that will hold all .NET projects for github.com/opentracing AND github.com/opentracing-contrib.

* Create an AppVeyor account with a general OpenTracing email address and password (maybe the same that has been used for the "OpenTracing" nuget.org user?) -> [Signup page](https://ci.appveyor.com/signup). 
  * This will be the user-independent account owner. You can add individuals later.
* Set the account name to "opentracing" on the [account page](https://ci.appveyor.com/account). This will ensure that all projects will have an URL of e.g. https://ci.appveyor.com/project/opentracing/opentracing-csharp
* On the [account page](https://ci.appveyor.com/account) you now have to link AppVeyor with Github. The GitHub user must be someone who has admin-rights in the github.com/opentracing and github.com/opentracing-contrib orgs.
  * This authorization can always be updated if, for whatever reason, the person e.g. leaves these github orgs.
* On the [project](https://ci.appveyor.com/projects) page, add the following github projects:
  * opentracing/opentracing-csharp
  * opentracing/basictracer-csharp (not sure if we'll do something there but you can still add it)
  * opentracing-contrib/csharp-netcore
* Add individuals on the [Team](https://ci.appveyor.com/team) page. These people will be able to access the projects that have been added to the account. Would be great if you could add me as an `Administrator` - my email is christian@chwe.at 
* As a user who has at least `Collaborator` rights in github.com/opentracing and github.com/opentracing-contrib, create [a new personal access token](https://github.com/settings/tokens) in Github with the right "public_repo". Copy the token and [encrypt it](https://ci.appveyor.com/tools/encrypt) in AppVeyor. Comment the output here. (this encrypted token will be committed)
* Sign in as the "OpenTracing" user on [nuget.org](https://www.nuget.org/users/account/LogOn?returnUrl=%2F) and [create a new API key](https://www.nuget.org/account/ApiKeys) with the following permissions:
  * Key name: "AppVeyor" (or something else - doesn't matter)
  * Expires in: 365 days
  * Push new packages and package versions
  * Glob pattern: "OpenTracing.*"
* Copy the generated key and, again, [encrypt it](https://ci.appveyor.com/tools/encrypt) in AppVeyor and comment the output here. We will use this to deploy releases to nuget.org

PS: If you use LastPass, you can also just share the username/password you've created, with me (christian@chwe.at) and let me do all of this :smile:

**Comment by MikeGoldsmith** [comment]
@cwe1ss  @tedsuo is this something we can move forward on? It would be nice to have this stuff automated instead of relying on manual packaging.

**Comment by cwe1ss** [comment]
I changed some things and I'll immediately merge it. I also created the AppVeyor account to speed things up but there's still a few things to do. I will add that to #81.

**Pull request merged**
