### PR TITLE
Decorators

### PR DESCRIPTION
**Pull request by jrouaix**
Proposition for some decorators around OpenTracing api. So we could be able to implement some metrics : https://github.com/opentracing/opentracing-csharp/issues/103

### CODE REVIEW

**Comment by jrouaix** [comment]
@cwe1ss Something we can discuss to get this PR accepted ?
Or perhaps you prefer these Decorators to be published as an independant project ?
Let me know please.

**Comment by jrouaix** [comment]
@cwe1ss is this project abandonned ?

**Comment by MikeGoldsmith** [comment]
Hi @jrouaix 

Sorry for the delay in reviewing your PR. This project is not abandoned.

I'll spend some time with it over the next day or two.

Thanks.

**Comment by MikeGoldsmith** [comment]
Hi @jrouaix 

I like what you've done and don't see any major issues, good work. However, the policy for the OpenTracing base projects is to be as clean and simple as possible with additional frameworks and patterns to be put into an additional repository / package. I'd be happy to help get a repo setup for this to be added to.

We want to keep the base projects as lean as possible, with just specification focused functionality. This enables us to keep those parts consistent & concise across all language implementations.

**Comment by jrouaix** [comment]
@MikeGoldsmith Thank you for the feedback. No problem to create a repo of my own.

> I'd be happy to help get a repo setup for this to be added to.

Where to start ?

**Comment by jrouaix** [comment]
Should I ask for a repo in https://github.com/opentracing-contrib ?

**Comment by tedsuo** [comment]
Hi @jrouaix, excited to see this! How does `csharp-decorators` sound as a repo name?

**Comment by MikeGoldsmith** [comment]
Thanks @tedsuo

**Comment by jrouaix** [comment]
@tedsuo @MikeGoldsmith Is there something I have to do to have the repo available and push the decorators ?

**Comment by MikeGoldsmith** [comment]
Hey @jrouaix - I'll find out what's going on and get it moving forward. I don't have direct access to create repo's on the contrib account.

**Comment by ndrwrbgs** [comment]
:) I can’t believe I missed this earlier. It’s the OOP analog to the Functional EventHooks tracer I had, nice!

**Comment by austinlparker** [comment]
@MikeGoldsmith @jrouaix I've created https://github.com/opentracing-contrib/csharp-decorators and added both of you with write permissions.

**Comment by tedsuo** [comment]
Whoop! thanks @austinlparker. Sorry about the wait, @jrouaix!

**Comment by jrouaix** [comment]
Awesome ... but ...
@austinlparker sorry I don't manage to write anything on the repo. (neither can I fork it since it's empty)
@MikeGoldsmith do you succeed to write something ?

**Comment by austinlparker** [comment]
@jrouaix I added you as a collaborator with write access, you still need to accept the invite. Please check your email and spam filter?

**Comment by cwe1ss** [comment]
Sorry for not responding earlier, work is really busy right now and I'm therefore keeping OSS work to a minimum. I agree that making this a contrib-project is the way to go here. Thanks for your contribution!

**Comment by jrouaix** [comment]
@austinlparker got it, thank you. Will publish soon

**Comment by jrouaix** [comment]
Ok moved here : https://github.com/opentracing-contrib/csharp-decorators
more to come

**Comment by MikeGoldsmith** [comment]
Thanks @jrouaix - good work!

**Pull request closed without merging**
