### PR TITLE
Add support for signing assemblies during build (#78)

### PR DESCRIPTION
**Pull request by MikeGoldsmith**

### CODE REVIEW

**Comment by MikeGoldsmith** [comment]
@cwe1ss I was just typing out the same message, I've just pushed the update to include the PublicSign attribute.

**Comment by MikeGoldsmith** [comment]
Tests now pass, but we need to be aware there are some consequences described [here](https://github.com/dotnet/cli/issues/6911#issuecomment-310099022).

From that link:
> However, since the binary is not actually fully signed, it cannot be installed to the GAC, cannot be used with shadow copying, and cannot be loaded in a partial trust context on full framework.

**Comment by cwe1ss** [comment]
Travis CI is just a "best effort" build environment anyway. I have to deploy to NuGet from a Windows machine as we also target "net45". I'm currently deploying from my local desktop but I want to set up AppVeyor at some point.

**Comment by MikeGoldsmith** [comment]
That's fair - I'm familiar with AppVeyor and can look into that integration if you like? I'll create a new issue for it.

**Comment by cwe1ss** [comment]
I'll merge this as there's (hopefully) not much to object. Just comment here or create a new issue if you have any further comments.

Thanks @MikeGoldsmith !

**Pull request merged**
